version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: webconnector-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-webconnector}
      POSTGRES_USER: ${POSTGRES_USER:-webuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-webpass}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:


