name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Tidy
        run: go mod tidy
      - name: Build
        shell: bash
        run: |
          if [ -d cmd/webconnector ]; then
            go build ./cmd/webconnector
          else
            echo "cmd/webconnector not found, building module root"
            go build .
          fi
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test ./...

